### ISSUE TITLE
SSL_ERROR_BAD_CERT_DOMAIN with HTTPS

### ISSUE THREAD

**Issue by xKiraiChan** [ChilloutVR-BepInEx-Modders/ChilloutVR-BepInEx-Modders.github.io#1]
The certificate is only valid for the following names: 
- `*.github.com`
- `www.github.com`
- `github.io`
- `github.com`
- `*.github.io`
- `githubusercontent.com`
- `*.githubusercontent.com`

The link in the repository's description is for `https`
<sub><sup>first issue moment</sup></sub>

**Comment by ljoonal** [comment]
Yeee working on that, currently Github just says
>  DNS Check in Progress 
and links to https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages#https-errors

That's why this hasn't been announced yet, since might just require to wait a few hours for that. If it doesn't fix itself magically though will need to poke @MilchZocker about re-doing the domain verification setup again.

**Comment by ljoonal** [comment]
Switched to the Github managed domain for now, can get custom domain later if there's a need, but it's too much of a hassle trying to use a custom domain for getting started at least.
